spring:
  datasource:
    username: root
    password: developer
  redis:
    host: localhost
    port: 6379
    password:
    database: 11
#    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  swagger:
    enabled: true # swagger是否启动
  servlet:
    multipart:
      location: /Users/Shared/filetemp # 临时目录,上传图片用，需要手动创建
knife4j:
  enable: true
  #  markdowns: classpath:markdown/*
  basic:
    enable: true
    username: developer
    password: developer2023
common:
  env: dev # EnumEnv
  files:
    savePath: /Users/Shared/file
jtd:
  runOnStartUp: true
  runType: createModifyDeleteAll # 注意 EnumSqlRunType.createModifyDeleteAll 会删除代码移除的字段
logging:
  level:
    com.pro: DEBUG
    com.baomidou.mybatisplus.mapper: DEBUG
    org.springframework.web.socket: DEBUG
